import fs from "fs";
import path from "path";
import { runIndexer } from "./documentIndexer.js";
import { matchTendersWithFolders } from "./tenderFolderMatcher.js";
import { indexFolderFiles } from "./fileIndexer.js";

// Configuration
const CONFIG = {
  syncLogsPath: path.resolve(process.cwd(), "data", "sync_logs.json"),
  tendersCachePath: path.resolve(process.cwd(), "data", "tender_cache.json"),
  syncIntervalMs: 30 * 60 * 1000, // 30 minutes
  maxRetries: 3,
  retryDelayMs: 5000
};

// Ensure data directory exists
const dataDir = path.dirname(CONFIG.syncLogsPath);
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

let isSyncRunning = false;
let pipelineTimer = null;

/**
 * atomic JSON Database Store for sync logs
 */
class SyncLogStore {
  constructor(filePath) {
    this.filePath = filePath;
  }

  async load() {
    try {
      if (!fs.existsSync(this.filePath)) {
        return [];
      }
      const raw = await fs.promises.readFile(this.filePath, "utf-8");
      return JSON.parse(raw || "[]");
    } catch (e) {
      return [];
    }
  }

  async appendLog(logEntry) {
    const list = await this.load();
    list.push(logEntry);
    
    // Limit to last 100 logs
    if (list.length > 100) {
      list.shift();
    }

    const tempPath = `${this.filePath}.tmp`;
    try {
      await fs.promises.writeFile(tempPath, JSON.stringify(list, null, 2), "utf-8");
      await fs.promises.rename(tempPath, this.filePath);
    } catch (err) {
      console.error(`[SyncLogStore] Failed to save log: ${err.message}`);
    }
  }
}

const logStore = new SyncLogStore(CONFIG.syncLogsPath);

/**
 * Orchestrates the full synchronization pipeline:
 * 1. Fetch sheets (implicitly triggered by calling /api/tenders or serverless handler)
 * 2. Extract docket numbers and match costing attachment details
 * 3. Scan network folder directories to index folders (documentIndexer)
 * 4. Match primary tender records to scanned folder names (tenderFolderMatcher)
 * 5. Index files inside matched folders incrementally (fileIndexer)
 * 6. Update the database and log execution details
 */
export async function executeSyncPipeline(triggeredBy = "SYSTEM", attempt = 1) {
  if (isSyncRunning) {
    console.warn(`[SyncPipeline] Synchronization already in progress. Skipping duplicate scan.`);
    return { success: false, reason: "Already running" };
  }

  isSyncRunning = true;
  const startTime = Date.now();
  console.log(`[SyncPipeline] Starting execution pipeline (Attempt ${attempt}/${CONFIG.maxRetries}), Triggered by: ${triggeredBy}`);

  const logEntry = {
    id: crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(),
    startTime,
    endTime: null,
    status: "IN_PROGRESS",
    recordsProcessed: 0,
    matchedFolders: 0,
    filesIndexedCount: 0,
    triggeredBy,
    errors: null
  };

  try {
    // Step 1: Run directory scan over network location to update local folder index
    console.log("[SyncPipeline] Step 1/4: Running network directory scanner...");
    await runIndexer();

    // Step 2: Fetch tender data cache generated by the API
    console.log("[SyncPipeline] Step 2/4: Reading primary tender records...");
    let tenders = [];
    try {
      // In a live system, this fetch coordinates with GoogleSheetService.
      // Here, we load the compiled JSON data file cached by server.js.
      const tenderCachePath = path.resolve(process.cwd(), "excel_cache", "last_sheet_fetch.json");
      if (fs.existsSync(tenderCachePath)) {
        tenders = JSON.parse(await fs.promises.readFile(tenderCachePath, "utf-8"));
      } else {
        // Fallback to active memory check
        console.warn("[SyncPipeline] Cache sheet file not found. Skipping tender matching.");
      }
    } catch (e) {
      console.warn(`[SyncPipeline] Could not read cached tenders: ${e.message}`);
    }

    // Step 3: Load directory scanner index and execute tender-folder matching
    console.log("[SyncPipeline] Step 3/4: Executing tender and folder matching...");
    let matchedCount = 0;
    let filesIndexedCount = 0;

    const folderIndexDbPath = path.resolve(process.cwd(), "data", "document_index.json");
    if (fs.existsSync(folderIndexDbPath) && tenders.length > 0) {
      const folderIndex = JSON.parse(await fs.promises.readFile(folderIndexDbPath, "utf-8"));
      
      const matches = await matchTendersWithFolders(tenders, folderIndex);
      matchedCount = matches.filter(m => m.folderFound).length;

      // Step 4: Incremental file scan for matched folders
      console.log("[SyncPipeline] Step 4/4: Scanning files inside matched tender folders...");
      const fileIndexDbPath = path.resolve(process.cwd(), "data", "file_index.json");
      const existingFileDb = fs.existsSync(fileIndexDbPath) 
        ? JSON.parse(await fs.promises.readFile(fileIndexDbPath, "utf-8")) 
        : {};

      for (const match of matches) {
        if (match.folderFound && match.folderPath) {
          // Check modification metrics to enforce incremental indexing only
          let shouldScan = true;
          try {
            const folderStats = await fs.promises.stat(match.folderPath);
            const lastKnownScanTime = Object.values(existingFileDb)
              .filter((f) => f.parentFolderPath === match.folderPath)
              .reduce((max, f) => Math.max(max, f.indexedAt || 0), 0);

            // Avoid scanning if the folder's modified timestamp is older than our last index run
            if (folderStats.mtimeMs <= lastKnownScanTime) {
              shouldScan = false;
            }
          } catch (e) {
            // Folder access error or stats fetch failed
            shouldScan = true;
          }

          if (shouldScan) {
            try {
              const res = await indexFolderFiles(match.folderPath);
              filesIndexedCount += res.totalFilesIndexed;
            } catch (err) {
              console.error(`[SyncPipeline] Failed to index files in "${match.folderPath}": ${err.message}`);
            }
          }
        }
      }
    }

    // Log success
    logEntry.endTime = Date.now();
    logEntry.status = "SUCCESS";
    logEntry.recordsProcessed = tenders.length;
    logEntry.matchedFolders = matchedCount;
    logEntry.filesIndexedCount = filesIndexedCount;
    
    console.log(`[SyncPipeline] Pipeline execution succeeded in ${((logEntry.endTime - startTime) / 1000).toFixed(2)}s.`);
    await logStore.appendLog(logEntry);
    isSyncRunning = false;
    return { success: true, logEntry };

  } catch (err) {
    console.error(`[SyncPipeline] Error encountered: ${err.message}`);
    logEntry.endTime = Date.now();
    logEntry.status = "FAILED";
    logEntry.errors = err.message;
    await logStore.appendLog(logEntry);
    isSyncRunning = false;

    // Retry strategy
    if (attempt < CONFIG.maxRetries) {
      console.log(`[SyncPipeline] Retrying in ${CONFIG.retryDelayMs / 1000}s...`);
      await new Promise(resolve => setTimeout(resolve, CONFIG.retryDelayMs));
      return executeSyncPipeline(triggeredBy, attempt + 1);
    }

    return { success: false, error: err.message };
  }
}

/**
 * Starts the pipeline scheduler
 */
export function startPipelineScheduler() {
  if (pipelineTimer) return;

  // Execute immediately on startup
  executeSyncPipeline("SYSTEM");

  pipelineTimer = setInterval(() => {
    executeSyncPipeline("SYSTEM");
  }, CONFIG.syncIntervalMs);

  console.log(`[SyncPipeline] Scheduler active. Running every ${CONFIG.syncIntervalMs / 60000} minutes.`);
}

/**
 * Stops the scheduler
 */
export function stopPipelineScheduler() {
  if (pipelineTimer) {
    clearInterval(pipelineTimer);
    pipelineTimer = null;
    console.log("[SyncPipeline] Scheduler stopped.");
  }
}

/**
 * API route controller to trigger a manual synchronization.
 */
export async function manualSyncRouteHandler(req, res) {
  try {
    const result = await executeSyncPipeline("MANUAL");
    if (result.success) {
      return res.status(200).json({
        success: true,
        message: "Manual synchronization pipeline completed.",
        log: result.logEntry
      });
    } else {
      return res.status(503).json({
        success: false,
        message: "Pipeline skipped or failed.",
        details: result.reason || result.error
      });
    }
  } catch (err) {
    return res.status(500).json({
      success: false,
      error: err.message
    });
  }
}
